ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - SPELL_CSPELL
  - SPELL_LYCHEE
DISABLE_LINTERS:
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE
  - REPOSITORY_TRUFFLEHOG
SPELL_CSPELL_CONFIG_FILE: .cspell.json
APPLY_FIXES: none
# We do not want to check links in our workflows, they may contain templates,
# which will fail.
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: ^\.github\/workflows\/.*yml$