ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
DISABLE_LINTERS:
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .github/linters/mlc_config.json
APPLY_FIXES: none
