ENABLE_LINTERS:
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - SPELL_CSPELL
  - SPELL_LYCHEE
DISABLE_LINTERS:
  - REPOSITORY_TRIVY
  - REPOSITORY_GRYPE
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: .github/linters/mlc_config.json
SPELL_CSPELL_CONFIG_FILE: .cspell.json
APPLY_FIXES: none
