baseURL = "/"
title = "EGI Documentation"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = false

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"
#pygmentsStyle = "monokailight"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[outputs]
# home = [ "HTML", "RSS", "JSON"]
home = [ "HTML" ]
page = [ "HTML" ]

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

# Language configuration

[languages]
[languages.en]
title = "EGI Docs"
description = "EGI documentation"
languageName ="English"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
copyright = "EGI Foundation"
privacy_policy = "https://www.egi.eu/privacy-policy/"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/EGI-Federation/documentation"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
# github_project_repo = "https://github.com/google/docsy"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = ""

# Enable Algolia DocSearch
algolia_docsearch = false

#Enable offline search with Lunr.js
offlineSearch = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/EGI-Federation/documentation/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/EGI-Federation/documentation/issues/new">tell us how we can improve</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "Community discussions"
  url = "https://community.egi.eu"
  icon = "fa fa-envelope"
  desc = "Discussion and help from your fellow users"
[[params.links.user]]
  name ="Twitter"
  url = "https://twitter.com/EGI_eInfra"
  icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest news!"
# [[params.links.user]]
#  name = "Stack Overflow"
#  url = "https://example.org/stack"
#  icon = "fab fa-stack-overflow"
#  desc = "Practical questions and curated answers"
#  Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/EGI-Federation"
  icon = "fab fa-github"
  desc = "Development takes place here!"
# [[params.links.developer]]
#  name = "Slack"
#  url = "https://example.org/slack"
#  icon = "fab fa-slack"
#  desc = "Chat with other project developers"
# [[params.links.developer]]
#  name = "Developer mailing list"
#  url = "https://example.org/mail"
#  icon = "fa fa-envelope"
#  desc = "Discuss development issues around the project"
# XXX Maybe useful to add back this somewhere
# [[menu.shortcuts]]
# name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
# url = "https://github.com/EGI-Federation/EGI-Federation.github.io/archive/master.zip"
# weight = 11

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
