baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "EGI Documentation"
theme = "hugo-theme-docdock-master"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
editURL = "https://github.com/EGI-Foundation/documentation/edit/master/content"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> <label>Github repo</label>"
identifier = "ds"
url = "https://github.com/EGI-Foundation/documentation"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
url = "https://github.com/EGI-Foundation/EGI-Foundation.github.io/archive/master.zip"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> <label>EGI</label>"
identifier = "egi"
url = "https://www.egi.eu/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> <label>Credits</label>"
url = "/credits"
weight = 30
