---
language: "en-gb"
enabledLanguageIds:
  - markdown
dictionaries:
  - custom-words
  - allowed-words
patterns:
  - name: md
    # pattern: /^(\s*`{3,}).*\n[\s\S]*?^\1/gmix
    pattern: /^(`{3})plaintext[\s\S]*?^\1/gmix
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - >
        /^(`{3}) (plaintext|shell|terraform) [\s\S]*?^\1 /gmix
      - >
        `.*`
      - >
        <!--.*-->
ignorePaths:
  - ".github/actions/**"
  - ".github/workflows/**"
  - ".cspell.json"
  - "cspell.config.yml"
  - "cspell.yml"
dictionaryDefinitions:
  - name: custom-words
    path: ./.github/actions/spelling/expect.txt
    addWords: true
  - name: allowed-words
    path: ./.github/actions/spelling/allow.txt
    addWords: true
