---
language: "en-gb"
enabledLanguageIds:
  - markdown
dictionaries:
  - custom-words
  - allowed-words
patterns:
  - name: html_comment 
    pattern: /<!--.*-->/
  - name: markdown_code_block
    pattern: /```[\s\S]*?```/
  - name: simple_code
    pattern: /`.*`/
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - markdown_code_block
      - html_comment
      - simple_code
ignorePaths:
  - ".github/actions/**"
  - ".github/workflows/**"
  - ".cspell.json"
  - "cspell.config.yml"
  - "cspell.yml"
dictionaryDefinitions:
  - name: custom-words
    path: ./.github/actions/spelling/expect.txt
    addWords: true
  - name: allowed-words
    path: ./.github/actions/spelling/allow.txt
    addWords: true
