---
name: Delete pull request preview

on:
  pull_request:
    # Run when label is removed or pull request closed
    types: [unlabeled, closed]

jobs:
  build:
    # Do not run on forks, and only if "safe for preview" label is set
    if: |
      github.repository == 'EGI-Federation/documentation' &&
      ((github.event.action == 'unlabeled' && github.event.label.name == 'safe for preview') ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'safe for preview')))
    name: Build with Hugo
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "pr_previews"

      - name: Delete pull request preview and commit changes
        uses: EndBug/add-and-commit@v7
        with:
          remove: "-r public/${{ github.event.number }}"
          message: "Purge preview for PR ${{ github.event.number }}"
