---
name: github pages
# Setup and build files with hugo
# https://github.com/peaceiris/actions-hugo
# Deploy to GitHub pages
# https://github.com/peaceiris/actions-gh-pages

# XXX temporary for testing build in the PR
on: [push, pull_request]
# XXX to be used once confiremd it builds correctly
# on:
#   push:
#     branches:
#       - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the Docsy theme
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.66.0"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          # NodeJS 12 is maintained until 2022-04-30
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: EGI-Foundation/EGI-Foundation.github.io
          publish_dir: ./public
          # XXX Publish to a test branch
          publish_branch: test
