name: Check Markdown links

on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Check links on new changes
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
