---
name: Preview pull requests
# Setup and build files with hugo
# https://github.com/peaceiris/actions-hugo
# Deploy to GitHub pages
# https://github.com/peaceiris/actions-gh-pages

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: ${{ github.event.label.name == 'preview' }}
    name: Build with Hugo
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the Docsy theme
          submodules: recursive
          # Fetch all history for .GitInfo and .Lastmod
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.66.0"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          # NodeJS 12 is maintained until 2022-04-30
          node-version: "12.x"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm project with a clean slate
        run: npm ci

      - name: Build and minify using Hugo
        # Build in a directory specific to the PR number
        run: hugo --minify --destination public/${{ github.event.number }}

      - name: Deploy Pull Request preview
        # Deploy should not run on forks
        if: ${{ github.repository == 'EGI-Federation/documentation' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use GITHUB_TOKEN allowing to write to local repository
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Do not purge other files
          # XXX add a way to clean deployed PR that havbe been closed or merged
          keep_files: true
          # Accessible at http://docs.egi.eu/documentation/
          # XXX use a different domain
          # cname: docs.egi.eu
          publish_branch: pr_previews

      - name: Update Pull Request
        uses: actions/github-script@v4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Documentation preview deployed!\`
            Available at https://docs.egi.eu/documentation/${{ github.event.number }}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
