---
name: Spellcheck Action

on: [pull_request]

jobs:
  spell:
    name: Spellcheck
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on PR
          ref: ${{ github.event.pull_request.head.sha }}
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Run the spell check
      - uses: rojopolis/spellcheck-github-actions@0.30.0
        name: Spellcheck
        with:
          config_path: .github/linters/spellcheck.yml
